### ISSUE TITLE
cl-camera fails at do_install

### ISSUE THREAD

**Issue by gmbodnar** [compulab-yokneam/meta-compulab#1]
The new cl-camera module fails to install because cl-camera.png cannot be found in the work directory. I believe that `SRC_URI` is being overwritten because of the inclusion of machine-specific additions. I worked around this by using `SRC_URI_append_<machine_name>` instead of `SRC_URI_<machine_name>`.

**Comment by vraevsky** [comment]
Thanks for reporting on the issue, Fixed.
https://github.com/compulab-yokneam/meta-compulab/commit/df3a1ce56ffa071a6352351b9a27b45a64f75ad8

**Comment by gmbodnar** [comment]
That's great. I've synced and rebuilt with no issues.
